name:                llang
version:             0.1.0.0
github:              "githubuser/llang"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2026 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md
- examples/README.md
data-files:
- examples/dependent/free_index_must_fail.llang
- examples/dependent/implicit_binder_index.llang
- examples/dependent/lambda_beta.llang
- examples/dependent/vec.llang
- examples/lib/algebra/box_match.llang
- examples/lib/algebra/cart_monoid.llang
- examples/lib/algebra/cat.llang
- examples/lib/algebra/ccc.llang
- examples/lib/algebra/coherence_demo.llang
- examples/lib/algebra/loop_demo.llang
- examples/lib/algebra/monoid_to_string.llang
- examples/lib/algebra/peano.llang
- examples/lib/algebra/planar_monoid.llang
- examples/lib/algebra/ski.llang
- examples/lib/algebra/subdiagram_match.llang
- examples/lib/codegen/minifun/console.llang
- examples/lib/codegen/minifun/minifun.surface.llang
- examples/lib/effects/combined.llang
- examples/lib/modes/dual_discipline_surface.llang
- examples/lib/modes/dual_discipline_term_surface.llang
- examples/lib/modes/lnl.counit.term.llang
- examples/lib/modes/lnl.llang
- examples/lib/modes/quad_discipline.llang
- examples/lib/modes/staging.llang
- examples/lib/modes/staging_mode_map.llang
- examples/lib/modes/uf_cancel.llang
- examples/lib/pushout/category_bool_nat_base.llang
- examples/lib/pushout/comm_monoid.llang
- examples/lib/pushout/nat_bool.llang
- examples/lib/pushout/nat_bool_plus.llang
- examples/lib/pushout/pushout_basic.llang
- examples/lib/pushout/pushout_extend.llang
- examples/lib/surfaces/ccc_surface/ccc.llang
- examples/lib/surfaces/planar_monoid.ssa.surface.llang
- examples/lib/surfaces/template_splice_demo.surface.llang
- examples/lib/templates/state.template.llang
- examples/lib/terms/splice_source.llang
- examples/lib/terms/term_defs.llang
- examples/run/algebra/box_match.run.llang
- examples/run/algebra/cart_monoid.run.llang
- examples/run/algebra/cat.run.llang
- examples/run/algebra/ccc.run.llang
- examples/run/algebra/coherence_demo.run.llang
- examples/run/algebra/mode_map_demo.run.llang
- examples/run/algebra/monoid.run.llang
- examples/run/algebra/morphism_term.llang
- examples/run/algebra/no_dup_error.run.llang
- examples/run/algebra/peano.run.llang
- examples/run/algebra/planar_monoid.run.llang
- examples/run/algebra/ski.run.llang
- examples/run/codegen/simple_codegen.run.llang
- examples/run/codegen/logic_full_adder_codegen.run.llang
- examples/run/data/list.run.llang
- examples/run/doc/hello_doc.run.llang
- examples/run/effects/combined_with_handler.run.llang
- examples/run/foliation/basic_foliate.run.llang
- examples/run/modes/dual_discipline_term_surface.run.llang
- examples/run/modes/lnl.counit.run.llang
- examples/run/modes/lnl.unit.run.llang
- examples/run/modes/modality_rename_visible.run.llang
- examples/run/modes/quad_discipline_surface.run.llang
- examples/run/modes/staging.run.llang
- examples/run/modes/staging_mode_map.run.llang
- examples/run/modes/uf_cancel.run.llang
- examples/run/pushout/pushout_basic.run.llang
- examples/run/surfaces/implements_uses.run.llang
- examples/run/surfaces/planar_monoid.ssa.run.llang
- examples/run/surfaces/template_splice_demo.run.llang
- examples/run/templates/state.run.llang
- examples/run/terms/cart_monoid.term.run.llang
- examples/run/terms/stlc_bool.term.run.llang
- examples/run/terms/term_ref.run.llang
- stdlib/bool.llang
- stdlib/data/list.llang
- stdlib/effects/exception.template.llang
- stdlib/effects/nondet.llang
- stdlib/effects/writer.template.llang
- stdlib/nat.llang
- stdlib/struct.cartesian.llang
- stdlib/struct.planar.llang
- stdlib/struct.symmetric.llang
# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/llang#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- directory
- filepath
- megaparsec
- mtl
- parser-combinators
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  other-modules:
  - Strat.DSL.Template
  - Strat.Frontend.Compile
  - Strat.Poly.TypePretty

executables:
  llang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llang

tests:
  llang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llang
    - tasty
    - tasty-hunit
    - QuickCheck
    - tasty-quickcheck
    other-modules:
    - Test.NoPolyPrefixes
    - Test.Poly.Basic
    - Test.Poly.Rewrite
    - Test.Poly.CriticalPairs
    - Test.Poly.Morphism
    - Test.Poly.Pushout
    - Test.Poly.CCC
    - Test.Poly.Coherence
    - Test.Poly.DataMacro
    - Test.Poly.Dependent
    - Test.Poly.Helpers
    - Test.Poly.Foliation
    - Test.Poly.Acyclic
    - Test.Poly.Feedback
    - Test.Poly.ModeTheory
    - Test.Poly.Surface
    - Test.Poly.TypeModes
    - Test.Poly.NoLegacy
    - Test.Value.Doc
    - Test.Frontend.Pipeline
    - Test.Frontend.ExampleCodegen
    - Paths_llang
