name:                llang
version:             0.1.0.0
github:              "githubuser/llang"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2026 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md
- examples/README.md
- SPEC-LEGACY.md
data-files:
- examples/monoid.llang
- examples/monoid.syntax.llang
- examples/monoid.syntax.alt.llang
- examples/monoid.models.llang
- examples/monoid.models.int.llang
- examples/monoid.run.llang
- examples/monoid.alt.run.llang
- examples/cat.llang
- examples/cat.run.llang
- examples/ccc.llang
- examples/ccc.syntax.llang
- examples/ccc.run.llang
- examples/peano.llang
- examples/peano.syntax.llang
- examples/peano.models.llang
- examples/peano.run.llang
- examples/ski.llang
- examples/ski.syntax.llang
- examples/ski.run.llang
- examples/ccc_surface/ccc.doctrine.llang
- examples/ccc_surface/ccc.interface.llang
- examples/ccc_surface/stlc.surface.llang
- examples/ccc_surface/stlc.syntax.llang
- examples/ccc_surface/stlc.run.llang
- examples/ccc_surface/stlc.lam1.run.llang
- examples/ccc_surface/stlc.lam2.run.llang
- examples/ccc_surface/stlc.lam3.run.llang
- examples/ccc_surface/stlc.pair.run.llang
- examples/ccc_surface/stlc.runspec.llang
- examples/morphism_term.llang
- examples/pushout/category_bool_nat_base.llang
- examples/pushout/pushout_basic.llang
- examples/pushout/pushout_basic.run.llang
- examples/pushout/pushout_extend.llang
- examples/pushout/comm_monoid.llang
- examples/pushout/nat_bool.llang
- examples/pushout/nat_bool.models.llang
- examples/pushout/nat_bool.run.llang
- examples/pushout/nat_bool_plus.llang
- examples/pushout/nat_bool_plus.models.llang
- examples/pushout/nat_bool_plus.run.llang
- examples/pushout/ambiguous_model_restriction.llang
- examples/poly/README.md
- examples/poly/planar_monoid.poly.llang
- examples/poly/planar_monoid.run.llang
- examples/poly/planar_monoid.ssa.run.llang
- examples/poly/cart_monoid.poly.llang
- examples/poly/cart_monoid.run.llang
- examples/poly/cart_monoid.term.run.llang
- examples/poly/no_dup_error.run.llang
- examples/poly/subdiagram_match.poly.llang
- examples/poly/monoid_to_string.llang
- examples/runspec/multi.llang
- stdlib/syntax.llang
- stdlib/nat.llang
- stdlib/bool.llang
- stdlib/native.models.llang
- stdlib/struct.planar.llang
- stdlib/struct.symmetric.llang
- stdlib/struct.cartesian.llang

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/llang#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- directory
- filepath
- megaparsec
- mtl
- parser-combinators
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  llang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llang

tests:
  llang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llang
    - tasty
    - tasty-hunit
    - QuickCheck
    - tasty-quickcheck
    other-modules:
    - Test.Backend
    - Test.Kernel.Basic
    - Test.Kernel.CriticalPairsDependent
    - Test.Kernel.Coherence
    - Test.Kernel.CriticalPairs
    - Test.Kernel.DSL
    - Test.Kernel.Fixtures
    - Test.Kernel.Morphism
    - Test.Kernel.Pushout
    - Test.Kernel.SortCtorTele
    - Test.Kernel.Rewrite
    - Test.Kernel.RewriteSystem
    - Test.Kernel.Regression
    - Test.Kernel.FreeTele
    - Test.Frontend.ModelRestriction
    - Test.Frontend.SyntaxModel
    - Test.Frontend.Loader
    - Test.Frontend.Implements
    - Test.Surface
    - Test.Surface2.Term
    - Test.Surface2.Pattern
    - Test.Surface2.CoreEval
    - Test.Surface2.Determinism
    - Test.Surface2.Elab
    - Test.CLI
    - Test.CLI.Golden
    - Test.Poly.Basic
    - Test.Poly.Rewrite
    - Test.Poly.DSL
    - Test.Poly.Morphism
    - Paths_llang
