name:                llang
version:             0.1.0.0
github:              "githubuser/llang"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2026 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md
data-files:
- examples/monoid.llang
- examples/monoid.syntax.llang
- examples/monoid.syntax.alt.llang
- examples/monoid.models.llang
- examples/monoid.models.int.llang
- examples/monoid.run.llang
- examples/monoid.alt.run.llang
- examples/cat.llang
- examples/cat.run.llang
- examples/ccc.llang
- examples/ccc.syntax.llang
- examples/ccc.run.llang
- examples/peano.llang
- examples/peano.syntax.llang
- examples/peano.models.llang
- examples/peano.run.llang
- examples/ski.llang
- examples/ski.syntax.llang
- examples/ski.run.llang
- examples/ccc_surface/ccc.doctrine.llang
- examples/ccc_surface/ccc.interface.llang
- examples/ccc_surface/stlc.surface.llang
- examples/ccc_surface/stlc.syntax.llang
- examples/ccc_surface/stlc.run.llang
- stdlib/syntax.llang
- stdlib/models.llang

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/llang#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- directory
- filepath
- megaparsec
- mtl
- parser-combinators
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  llang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llang

tests:
  llang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llang
    - tasty
    - tasty-hunit
    - QuickCheck
    - tasty-quickcheck
    other-modules:
    - Test.Backend
    - Test.Kernel.Basic
    - Test.Kernel.CriticalPairsDependent
    - Test.Kernel.Coherence
    - Test.Kernel.CriticalPairs
    - Test.Kernel.DoctrineExpr
    - Test.Kernel.DSL
    - Test.Kernel.Fixtures
    - Test.Kernel.Relative
    - Test.Kernel.Rewrite
    - Test.Kernel.RewriteSystem
    - Test.Frontend.SyntaxModel
    - Test.Frontend.Loader
    - Test.Surface
    - Test.Surface2.Term
    - Test.Surface2.Pattern
    - Test.CLI
    - Paths_llang
